export const skills = [
  { src: "skills/javascript.svg", alt: "JavaScript" },
  { src: "skills/typescript.svg", alt: "TypeScript" },
  { src: "skills/java.svg", alt: "java" },
  { src: "skills/python.svg", alt: "python" },
  { src: "skills/bash.svg", alt: "bash" },
  { src: "skills/angular.png", alt: "angular" },
  { src: "skills/next-js.svg", alt: "next" },
  { src: "skills/node.svg", alt: "node" },
  { src: "skills/nestjs.svg", alt: "nestJs" },
  { src: "skills/spring-boot.svg", alt: "spring-boot" },
  { src: "skills/mongodb.svg", alt: "mongodb" },
  { src: "skills/mysql.svg", alt: "mysql" },
  { src: "skills/mongoose.svg", alt: "mongoose" },
  { src: "skills/git.svg", alt: "git" },
  { src: "skills/github.svg", alt: "github" },
  { src: "skills/docker.svg", alt: "docker" },
  // { src: "/ngrx.svg", alt: "ngrx" },
  // { src: "/redux.svg", alt: "redux" },
  // { src: "/tailwind.svg", alt: "tailwind" },
];
